name: pgai
services:

  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_PASSWORD: postgres
      OPENAI_API_KEY: 45d5b9dcd26f8e79591b2ceeda6a16640cdd0571cc2e2e285eee2ed1d816a541
      BASE_URL: https://api.together.xyz/v1
    ports:
      - "5432:5432"
    volumes:
      - data:/home/postgres/pgdata/data
    command: [ "-c", "ai.ollama_host=http://host.docker.internal:11434" ]

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/postgres
      OLLAMA_HOST: http://host.docker.internal:11434
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]
volumes:
  data:
